apiVersion: v1
kind: Service
metadata:
  name: system-monitoring-service
spec:
  type: NodePort
  selector:
    app: system-monitoring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
